blank_issues_enabled: true
contact_links:
  - name: Issue
    about: Issue template
    url: https://github.com/gas-helloworld/issues/new?template=issue.md&projects=gas-helloworld/1&labels=enhancement
